// Regenerates src/core/radars.data.ts from official open-data sources.
// Downloads server-side (no CORS); falls back to a local raw file for dev.
// Raw source files are NOT committed. This is what the CI cron job runs.
//
//   DGT       DATEX2 XML, fixed-radar cabins (CabinasCinemometro set), WGS84.
//             PK and direction, no speed limit.
//   Catalunya Servei Catala de Transit plain-text export, UTM 31N (ETRS89).
//             PK and speed limit, no direction.
//   Euskadi   Trafikoa cabinas-de-radar-fijo HTML page; each cabin is inlined
//             as JS (var x/y in UTM 30N ETRS89, popupValores for the rest).
//             PK, direction and speed limit.
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import {
  normalizeDgt,
  normalizeEuskadi,
  normalizeCatalunya,
  dedupeRadars,
  parseDataset,
  keepUnreachable,
  parseDgtXml,
  parseCatalunyaTxt,
  parseTrafikoaHtml,
} from './lib/radar-normalize.mjs'

const SRC = new URL('../data/raw/radar-sources/', import.meta.url)
const OUT = new URL('../src/core/radars.data.ts', import.meta.url)

const URLS = {
  dgt: 'http://infocar.dgt.es/datex2/dgt/PredefinedLocationsPublication/radares/content.xml',
  catalunya: 'http://transit.gencat.cat/web/.content/documents/seguretat_viaria/radars.txt',
  euskadi: 'https://apps.trafikoa.euskadi.eus/lfr/web/trafikoa/cabinas-de-radar-fijo',
}

// Trafikoa serves the radar page only to browser-like clients.
const UA = { 'User-Agent': 'Mozilla/5.0' }

// Coarse mainland+islands+Canary bounding box, used to discard corrupt rows.
const inSpain = (lat, lon) => lat > 27 && lat < 44 && lon > -19 && lon < 5

// Fetch a URL server-side; on failure fall back to a local raw file (dev).
async function fetchOrLocal(url, localName, headers) {
  try {
    if (url) {
      const res = await fetch(url, headers ? { headers } : undefined)
      if (res.ok) return Buffer.from(await res.arrayBuffer())
      console.warn(`fetch ${localName}: HTTP ${res.status}`)
    }
  } catch (e) {
    console.warn(`fetch failed for ${localName}: ${e.message}`)
  }
  const p = new URL(localName, SRC)
  if (existsSync(p)) {
    console.warn(`using local ${localName}`)
    return readFileSync(p)
  }
  console.warn(`no source for ${localName} - skipping`)
  return null
}

const [dgtBuf, catBuf, euskBuf] = await Promise.all([
  fetchOrLocal(URLS.dgt, 'dgt.xml'),
  fetchOrLocal(URLS.catalunya, 'catalunya.txt'),
  fetchOrLocal(URLS.euskadi, 'euskadi.html', UA),
])

const fresh = {
  dgt: normalizeDgt(parseDgtXml(dgtBuf)),
  catalunya: normalizeCatalunya(parseCatalunyaTxt(catBuf)),
  euskadi: normalizeEuskadi(parseTrafikoaHtml(euskBuf)),
}
for (const [name, list] of Object.entries(fresh)) {
  console.log(`  ${name}: ${list.length} rows`)
}
const previous = existsSync(OUT) ? parseDataset(readFileSync(OUT, 'utf8')) : null
const { bySource, kept, missing } = keepUnreachable(fresh, previous)
if (missing.length > 0) {
  console.error(`no radars from ${missing.join(', ')} and none to keep - aborting`)
  process.exit(1)
}
for (const k of kept) {
  console.warn(`${k.source} unreachable - keeping its ${k.count} radars from ${k.since}`)
}

const all = dedupeRadars(
  [...bySource.dgt, ...bySource.catalunya, ...bySource.euskadi].filter((r) =>
    inSpain(r.lat, r.lon),
  ),
)
if (all.length === 0) {
  console.error('no radars produced - aborting')
  process.exit(1)
}

const round = (n) => Math.round(n * 1e5) / 1e5
const body = all
  .map(
    (r) =>
      `  { id: ${JSON.stringify(r.id)}, lat: ${round(r.lat)}, lon: ${round(r.lon)}, ` +
      `via: ${JSON.stringify(r.via)}, source: ${JSON.stringify(r.source)}` +
      (r.pk !== undefined ? `, pk: ${r.pk}` : '') +
      (r.dir ? `, dir: ${JSON.stringify(r.dir)}` : '') +
      (r.limit !== undefined ? `, limit: ${r.limit}` : '') +
      ` },`,
  )
  .join('\n')
const generatedOn = new Date().toISOString().slice(0, 10)
writeFileSync(
  OUT,
  `// GENERATED by scripts/build-radars.mjs - do not edit by hand.\n` +
    `import type { Radar } from './radars'\n` +
    kept.map((k) => `// kept: ${k.source} from ${k.since}\n`).join('') +
    `\n` +
    `export const RADARS_DATASET_DATE = '${generatedOn}'\n\n` +
    `export const RADARS: readonly Radar[] = [\n${body}\n]\n`,
)
console.log(`Wrote ${all.length} radars (date ${generatedOn}).`)
