// Regenerates src/core/places.data.ts, the municipalities a person can pick by
// hand when the browser will not share a location. Built from the Ministerio's
// nationwide station listing (the same API the app reads prices from), so the
// list holds exactly the places that have a station to show.
// Downloads server-side; falls back to a local raw file for dev. Nothing here
// runs in a browser and no geocoding service is ever contacted.
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { placesFromStations } from './lib/places-normalize.mjs'

const SRC = new URL('../data/raw/places-sources/stations.json', import.meta.url)
const OUT = new URL('../src/core/places.data.ts', import.meta.url)
const URL_ALL =
  'https://sedeaplicaciones.minetur.gob.es/ServiciosRESTCarburantes/PreciosCarburantes/EstacionesTerrestres/'

async function load() {
  try {
    const res = await fetch(URL_ALL)
    if (res.ok) return await res.json()
    console.warn(`fetch stations: HTTP ${res.status}`)
  } catch (e) {
    console.warn(`fetch failed for stations: ${e.message}`)
  }
  if (existsSync(SRC)) {
    console.warn('using local stations.json')
    return JSON.parse(readFileSync(SRC, 'utf8'))
  }
  return null
}

const data = await load()
const places = placesFromStations(data?.ListaEESSPrecio ?? [])
// Spain has some 3,200 municipalities with a station; far fewer means a
// partial or changed response, and the previous dataset is better than that.
if (places.length < 2000) {
  console.error(`only ${places.length} places produced - aborting`)
  process.exit(1)
}

const provinces = [...new Set(places.map((p) => p.province))].sort((a, b) => a.localeCompare(b, 'es'))
const provinceIndex = new Map(provinces.map((p, i) => [p, i]))
const body = places
  .map((p) => `  [${JSON.stringify(p.name)}, ${provinceIndex.get(p.province)}, ${p.lat}, ${p.lon}, ${p.n}],`)
  .join('\n')
const generatedOn = new Date().toISOString().slice(0, 10)
writeFileSync(
  OUT,
  `// GENERATED by scripts/build-places.mjs - do not edit by hand.\n` +
    `// Rows: [name, province index, lat, lon, station count].\n` +
    `import type { PlaceRow } from './places'\n\n` +
    `export const PLACES_DATASET_DATE = '${generatedOn}'\n\n` +
    `export const PLACE_PROVINCES: readonly string[] = ${JSON.stringify(provinces)}\n\n` +
    `export const PLACE_ROWS: readonly PlaceRow[] = [\n${body}\n]\n`,
)
console.log(`Wrote ${places.length} places in ${provinces.length} provinces (date ${generatedOn}).`)
